# cloudbuild.yaml
steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/electronic_exam', '.']

  # Step 2: Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/electronic_exam']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'electronic-exam',
        '--image', 'gcr.io/$PROJECT_ID/electronic_exam',
        '--platform', 'managed',
        '--region', 'asia-southeast1',
        '--allow-unauthenticated',
        '--port', '8080',
        '--set-env-vars',
        'DJANGO_SECRET_KEY=django-insecure-t&ri-woq=wx@da@jwe%#soj(9ri9un%b@yzx3aq!m@g#q-*@n1,DEBUG=True,ALLOWED_HOSTS=https://exim-142442460469.asia-southeast1.run.app,OPENAI_API_KEY=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',
      ]

images:
  - 'gcr.io/$PROJECT_ID/electronic_exam'
