# Generated by Django 3.2 on 2026-01-12 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board_exam', '0002_auto_20260112_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='course',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='result',
            name='exam_id',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='result',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='result',
            name='student_id',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='result',
            name='student_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='result',
            name='subject',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='result',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('user', 'subject')},
        ),
    ]
