# Generated by Django 3.2 on 2026-02-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_exam', '0003_auto_20260112_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
